### ISSUE TITLE
Basic Setup Question.

### ISSUE THREAD

**Issue by princessGasmask** [Liath/Twi#2]
I am attempting to set this up on a Win10 machine. Is Heroku mandatory for the program to start?

**Comment by Liath** [comment]
Not really but Heroku does simplify things. You'll need to install redis
and nodejs.

**Comment by princessGasmask** [comment]
Okay. The instructions seemed pretty straightforward, but I'm more used to PHP things and I'm still learning how to setup Node.JS scripts without messing up. I get
[npm-debug.log.txt](https://github.com/Liath/Twi/files/517458/npm-debug.log.txt) whenever I try to npm run. I already did npm install. Is this because I NEED MongoDB, or is this a Redis issue?

**Comment by princessGasmask** [comment]
Sorry for double posting. I made progress in getting MongoDB setup and everything. However, the server states that Twi is on port 3000. Once I try localhost:3000, it just brings up the same Welcome screen as though I was connecting to port 80. I also tried port 27017 and was greeted with a "It looks like you are trying to access MongoDB over HTTP on the native driver port." message. I feel like I'm so close.

**Comment by Liath** [comment]
Your log file is a little confusing. Is there a particular reason you have
this app under your Apache root directory?

**Comment by princessGasmask** [comment]
It's the default web root in Xampp, and it's usually simpler than creating
a ton of Virtual Hosts.

**Comment by Liath** [comment]
You don't happen to have Apache running on port 3000 at the same time as
node, do you?

**Comment by Liath** [comment]
I've never attempted this but this SO looks like it might be helpful:
http://stackoverflow.com/questions/9831594/apache-and-node-js-on-the-same-server

**Comment by princessGasmask** [comment]
I tried having them both running 3000 and using the link. Now I get a generic server error splash. I guess I'll just try it with Heroku if it's easier.

**Comment by princessGasmask** [comment]
Okay. This is my last shot for the night before I go to bed. Sorry to be such a bother. I'm attempting to install through Heroku, but this is the output. set TWI_SETTINGS=`node -e "console.log(JSON.stringify(require('./settings.js')));"
 !    -e is invalid. Must be in the format FOO=bar.

**Comment by Liath** [comment]
That command was intended to be run on Linux. Idk what the Windows
equivalent would look like, perhaps try running it in PowerShell? I'm out
camping so I won't be able to check until Monday.

**Comment by Liath** [comment]
Haven't had a chance to test, but some quick googling reveals that the command is likely something like this:
`heroku config:set TWI_SETTINGS=$(node -e "console.log(JSON.stringify(require('./settings.js')));")`

**Comment by princessGasmask** [comment]
still get the message  -e is invalid. Must be in the format FOO=bar.

**Comment by Liath** [comment]
I mean, just convert the contents of `./settings.js` to JSON and pass that.
You could probably do something like saving `console.log(JSON.stringify(require('./settings.js')));` to a file, maybe `tojson.js`. Then the config line would be set with `heroku config:set TWI_SETTINGS=$(node tojson.js)`
